[window]
opacity = 1
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
size = 8.5
offset.x=0
offset.y=4

# Colors (Oxocarbon)
# Source https://vimcolorschemes.com/nyoom-engineering/oxocarbon.nvim
# Colors (Oceanic Next)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#d8dee9'

# Normal colors
[colors.normal]
black   = '#29414f'
red     = '#ec5f67'
green   = '#99c794'
yellow  = '#fac863'
blue    = '#6699cc'
magenta = '#c594c5'
cyan    = '#5fb3b3'
white   = '#65737e'

# Bright colors
[colors.bright]
black   = '#405860'
red     = '#ec5f67'
green   = '#99c794'
yellow  = '#fac863'
blue    = '#6699cc'
magenta = '#c594c5'
cyan    = '#5fb3b3'
white   = '#adb5c0'

