# Theming
font: JetBrainsMono Nerd Font 12
background: "#191724b0"
color: "#e0def4"
border: "#31748f"
separator: " - "
border_width: 1
corner_r: 10
padding: 15
anchor: center
inhibit_compositor_keyboard_shortcuts: true
menu:
  - key: "f"
    desc: zen-browser 
    cmd: zen-browser
  - key: "t"
    desc: Google Calendar
    cmd: zen-browser https://calendar.google.com
  - key: "o"
    desc: Obsidian
    cmd: obsidian
  - key: "g"
    desc: GitHub
    submenu:
      - key: "p"
        desc: Profile (PS-Wizard)
        cmd: zen-browser https://github.com/PS-Wizard/
      - key: "d"
        desc: Dotfiles
        cmd: zen-browser https://github.com/PS-Wizard/Dotfiles
      - key: "s"
        desc: School
        cmd: zen-browser https://github.com/PS-Wizard/School
  - key: "l"
    desc: AI
    submenu:
      - key: "1"
        desc: Claude
        cmd: zen-browser https://claude.ai
      - key: "2"
        desc: ChatGPT
        cmd: zen-browser https://chatgpt.com
      - key: "3"
        desc: Gemini
        cmd: zen-browser https://gemini.google.com
      - key: "4"
        desc: Notebooklm
        cmd: zen-browser https://notebooklm.google.com/
  - key: "u"
    desc: Usage Limits Codex
    submenu:
      - key: "l"
        desc: Chatgpt Codex Usage Limits
        cmd: zen-browser https://chatgpt.com/codex/settings/usage
  - key: "n"
    desc: Gammastep
    submenu:
      - key: "1"
        desc: Warm (4500K)
        cmd: pkill gammastep; gammastep -O 4500
      - key: "2"
        desc: Warmer (3500K)
        cmd: pkill gammastep; gammastep -O 3500
      - key: "3"
        desc: Warmest (3000K)
        cmd: pkill gammastep; gammastep -O 3000
      - key: "4"
        desc: Warmest + Dim (3000K 70%)
        cmd: pkill gammastep; gammastep -O 3000 -b 0.7
      - key: "0"
        desc: Off
        cmd: pkill gammastep
  - key: "d"
    desc: Wayscriber
    cmd: pkill wayscriber; wayscriber --active --mode whiteboard
  - key: "w"
    desc: Waybar
    submenu:
      - key: "r"
        desc: Reload
        cmd: pkill waybar && waybar -c ~/.config/waybar/config.json -s ~/.config/waybar/style.css
  - key: "m"
    desc: Mirror Display
    cmd: wl-mirror $(niri msg --json outputs | jq -r '.[] | select(.logical.x == 0 and .logical.y == 0) | .name')
  - key: "r"
    desc: Recording
    submenu:
      - key: "r"
        desc: Record (no audio)
        submenu:
          - key: "3"
            desc: 30 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 30 -fm cfr -q medium -k h264 -encoder gpu -o ~/recording.mp4
          - key: "6"
            desc: 60 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 60 -fm cfr -q medium -k h264 -encoder gpu -o ~/recording.mp4
          - key: "1"
            desc: 120 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 120 -fm cfr -q medium -k h264 -encoder gpu -o ~/recording.mp4
          - key: "q"
            desc: kill
            cmd: killall gpu-screen-recorder

      - key: "a"
        desc: Record (with audio)
        submenu:
          - key: "3"
            desc: 30 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 30 -fm cfr -q medium -k h264 -encoder gpu -a default_output -o ~/recording.mp4
          - key: "6"
            desc: 60 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 60 -fm cfr -q medium -k h264 -encoder gpu -a default_output -o ~/recording.mp4
          - key: "1"
            desc: 120 FPS
            cmd: gpu-screen-recorder -w eDP-2 -f 120 -fm cfr -q medium -k h264 -encoder gpu -a default_output -o ~/recording.mp4

  - key: "s"
    desc: Fan Control
    submenu:
      - key: "1"
        desc: 25% (Silent-ish)
        cmd: nbfc set -s 25
      - key: "2"
        desc: 50% (Balanced)
        cmd: nbfc set -s 50
      - key: "3"
        desc: 75% (Performance)
        cmd: nbfc set -s 75
      - key: "4"
        desc: 100% (Jet Engine)
        cmd: nbfc set -s 100
      - key: "0"
        desc: Auto
        cmd: nbfc set -a

  - key: "q"
    desc: Stop Recording
    cmd: killall gpu-screen-recorder
