## name: Nemo Warm
## blurb: Warm Gruvbox-inspired palette on pure black

background               #000000
foreground               #d4c7a1

# Selection — same idea as your PmenuSel
selection_foreground     #1d2021
selection_background     #a89984

# Cursor
cursor                   #d4c7a1
cursor_text_color        #1d2021

# URLs
url_color                #7daea3

# Tabs
active_tab_foreground    #1d2021
active_tab_background    #a89984

inactive_tab_foreground  #7c6f64
inactive_tab_background  #1c1b18

# black
color0                    #282621
color8                    #665c54

# red
color1                    #cc6b64
color9                    #ea6962

# green
color2                    #a9b665
color10                   #b8bb26

# yellow
color3                    #d8a657
color11                   #fabd2f

# blue
color4                    #7daea3
color12                   #83a598

# magenta
color5                    #d3869b
color13                   #d3869b

# cyan
color6                    #89b482
color14                   #8ec07c

# white
color7                    #d4c7a1
color15                   #ebdbb2
