## name: nemo
## source: /home/wizard/.config/nvim/lua/themes/nemo/palette.lua
## source: /home/wizard/.config/nvim/lua/themes/nemo/palette.lua
foreground               #dadada
background               #000000
# background               #191724
selection_foreground     #10171a
selection_background     #9bdead
cursor                   #67b0e8
cursor_text_color        #10171a
url_color                #67b0e8
active_tab_foreground    #dadada
active_tab_background    #1e2528
inactive_tab_foreground  #464d50
inactive_tab_background  #141b1e
# black
color0   #10171a
color8   #3c4346
# red
color1   #e57474
color9   #f48383
# green
color2   #8ccf7e
color10  #86d988
# yellow
color3   #e5c76b
color11  #edcf73
# blue
color4   #67b0e8
color12  #5aa3db
# magenta
color5   #c47fd5
color13  #b570c6
# cyan
color6   #6cbfbf
color14  #9bdead
# white
color7   #dadada
color15  #e4e4e4
